config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'control#index'
    get 'moderation', to: 'moderation#index'
    get 'email', to: 'control#email'
    get 'stats', to: 'stats#index'
    resources :reports do
      get :delete_content
      get :resolve
      get :deny
      get :reopen
      get :close
    end
    scope '/lists' do
      get 'users', to: 'listings#users'
      post 'add_blogger', to: 'listings#add_blogger'
      post 'remove_blogger', to: 'listings#remove_blogger'
      post 'mass_moderation', to: 'listings#moderate'
    end
  end

  post 'ban_user', to: 'application#ban_user'
    post 'unban_user', to: 'application#unban_user'

  get '/c/:category', to: 'submissions#index', as: 'category'
  get '/all', to: 'submissions#index'
  get '/search', to: 'submissions#search', as: 'search'

  # Users
  devise_for :users, :controllers => { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks', :passwords => 'usesr/passwords' }  
  get '/u/:user', to: 'submissions#user', as: 'user_uploads'
  get '/accounts/finish_steam', to: 'application#finish_steam', as: 'finish_steam'
  # Root
  root 'home#home'

  get '/home', to: 'home#home'

  # About Page
  get :about, to: 'home#about'

  # Submissions
  get '/projects/:type', to: 'submissions#index', as: 'projects', defaults: { :type => 'all' }
  resources :submissions do
    # Latest download
    get :download
    resources :comments do
      get :restore
    end
    resources :uploads do
      post :approve
      post :deny
      # Download specific version
      get :download
    end
    resources :images, :only => [:edit, :create, :destroy, :new]
    get :favorite
    resources :videos
    resources :reports
  end

  namespace :blog do
    get '/', to: 'posts#index'
    resources :posts
  end

  resources :uploads do
    post :approve
    post :deny
  end

  resources :comments do
    resources :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/documentation', to: 'documentation#index', defaults: { format: 'html' }
      resources :submissions, :only => [:show, :index], defaults: { :sort => 'popular', :type => 'all' } do
        resources :comments, :only => [:show, :index]
        resources :uploads, :only => [:show, :index]
      end
      scope 'stats' do
        get :submissions, :to => 'submissions#stats'
        get :uploads, :to => 'uploads#stats'
        get :comments, :to => 'comments#stats'
      end
    end
  end

  scope '/api/v0' do
    get '/news', to: 'application#news'
    post '/contact', to: 'application#contact', as: 'contact'
    get '/flush', to: 'application#flush_cache', as: 'flush_cache'
    post '/email', to: 'application#send_email', as: 'email'
  end

  get '/unsubscribe', to: 'application#unsubscribe', as: 'unsubscribe'
end

app/models/blog/post.rb
class Blog::Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :title, type: String
  field :body, type: String
  field :baked_body, type: String

  validates :title, presence: true
  validates :body, presence: true
  validates :baked_body, presence: true

  belongs_to :author, class_name: 'User', inverse_of: 'blog_posts'

  before_validation :bake_body

  slug :title, history: true

  def bake_body
  	self.baked_body = body.bbcode_to_html.gsub(/[\r\n]+/, "<br>")
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
	before_filter :set_post, only: [:edit, :update, :show, :destroy]
	before_filter :authenticate_user!, only: [:new, :edit, :create, :destroy]

	def index
		@posts = Blog::Post.all
	end

	def new
		redirect_to blog_posts_path unless current_user.can_blog || user_is_admin
		@post = Blog::Post.new
	end

	def edit
		redirect_to blog_posts_path unless (current_user.can_blog && @post.author == current_user) || user_is_admin
	end

	def show
	end

	def create
		redirect_to blog_posts_path unless current_user.can_blog || user_is_admin
		@post = Blog::Post.new(post_params)
		current_user.blog_posts << @post
		if @post.save
			redirect_to @post, notice: "Successfully saved a blog post."
		else
			render 'edit', alert: "Please correct the outstanding issues and save the blog post again."
		end
	end

	def update
		redirect_to blog_posts_path unless (current_user.can_blog && @post.author == current_user) || user_is_admin
		if @post.update!(post_params)
			redirect_to @post, notice: "Successfully updated a blog post."
		else
			render 'edit', alert: "Please correct the outstanding issues and save the blog post again."
		end
	end

	def destroy
		redirect_to blog_posts_path unless (current_user.can_blog && @post.author == current_user) || user_is_admin
		@post.destroy
		redirect_to blog_posts_path, notice: "Successfully deleted a blog post."
	end

	private
	def set_post
		@post = Blog::Post.find(params[:id])
	end

	def post_params
		params.require(:blog_post).permit(:title, :body)
	end
end

app/views/blog/posts/_form.html.erb
<div id="centerpage">
  <%= render 'shared/tabs' %>
  <div class="box effect1">
    <h2><%= t('blog.posts.new_post') %></h2>
  </div>        
  <div id="mainpage"> 
    <%= form_for @post do |f| %>
      <%= render 'shared/errors', object: @post %>
      <div class='form-input'>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="form-input">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 10 %>
        <p class='hint'>Mods-Unturned uses <a href="https://en.wikipedia.org/wiki/BBCode">BBCode</a> to format blog posts. See the link for formatting hints.</p>
      </div>
      <div class="form-input">
        <%= f.submit 'Save' %>
      </div>
    <% end %>   
</div>

app/views/blog/posts/edit.html.erb
<%= render 'form' %>

app/views/blog/posts/index.html.erb
<div id="centerpage">
  <%= render 'shared/tabs' %>
  <div class="box effect1">
    <h2><%= t('.blog_posts') %></h2>
  </div>        
  <div id="mainpage">
    <% if (current_user && current_user.can_blog && @post.author == current_user) || user_is_admin %>
      <div class="management">
        <%= link_to 'New Post', new_blog_post_path %>
        <% if user_is_admin %>
          <span> | </span>
          <%= link_to 'Manage Bloggers', admin_users_path %>
        <% end %>
      </div>
    <% end %>
    <% @posts.each do |post| %>
      <h3><%= post.title %> <span class='post-author'>by <%= link_to post.author.username, user_uploads_path(post.author.username) %></span></h3>
      <hr>
      <p><%= raw post.baked_body.to_html %></p>
    <% end %>
  </div>    
</div>

app/views/blog/posts/new.html.erb
<%= render 'form' %>

app/views/blog/posts/show.html.erb
<div id="centerpage">
  <%= render 'shared/tabs' %>
  <div class="box effect1">
    <h2><%= @post.title %></h2>
  </div>        
  <div id="mainpage">
    <% if (curent_user && current_user.can_blog && @post.author == current_user) || user_is_admin %>
    <div class="management">
      <%= link_to 'Edit', edit_blog_post_path(@post) %>
      <span> | </span>
      <%= link_to 'Delete', blog_post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this blog post?" } %>
    </div>
    <% end %>
    <div class="blogpost">
      <h1>
      <%= @post.title %>
      <span class='post-author'>by: <%= link_to @post.author.username, user_uploads_path(@post.author.username) %></span>
      <hr style="width: auto;">
      </h1>
      <p><%= raw @post.baked_body.to_html %></p>
    </div>
  </div>    
</div>