config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'control#index'
    get 'moderation', to: 'moderation#index'
    get 'email', to: 'control#email'
    get 'stats', to: 'stats#index'
    resources :reports do
      get :delete_content
      get :resolve
      get :deny
      get :reopen
      get :close
    end
    scope '/lists' do
      get 'users', to: 'listings#users'
      post 'add_blogger', to: 'listings#add_blogger'
      post 'remove_blogger', to: 'listings#remove_blogger'
      post 'mass_moderation', to: 'listings#moderate'
    end
  end

  post 'ban_user', to: 'application#ban_user'
    post 'unban_user', to: 'application#unban_user'

  get '/c/:category', to: 'submissions#index', as: 'category'
  get '/all', to: 'submissions#index'
  get '/search', to: 'submissions#search', as: 'search'

  # Users
  devise_for :users, :controllers => { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks', :passwords => 'usesr/passwords' }  
  get '/u/:user', to: 'submissions#user', as: 'user_uploads'
  get '/accounts/finish_steam', to: 'application#finish_steam', as: 'finish_steam'
  # Root
  root 'home#home'

  get '/home', to: 'home#home'

  # About Page
  get :about, to: 'home#about'

  # Submissions
  get '/projects/:type', to: 'submissions#index', as: 'projects', defaults: { :type => 'all' }
  resources :submissions do
    # Latest download
    get :download
    resources :comments do
      get :restore
    end
    resources :uploads do
      post :approve
      post :deny
      # Download specific version
      get :download
    end
    resources :images, :only => [:edit, :create, :destroy, :new]
    get :favorite
    resources :videos
    resources :reports
  end

  namespace :blog do
    get '/', to: 'posts#index'
    resources :posts
  end

  resources :uploads do
    post :approve
    post :deny
  end

  resources :comments do
    resources :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/documentation', to: 'documentation#index', defaults: { format: 'html' }
      resources :submissions, :only => [:show, :index], defaults: { :sort => 'popular', :type => 'all' } do
        resources :comments, :only => [:show, :index]
        resources :uploads, :only => [:show, :index]
      end
      scope 'stats' do
        get :submissions, :to => 'submissions#stats'
        get :uploads, :to => 'uploads#stats'
        get :comments, :to => 'comments#stats'
      end
    end
  end

  scope '/api/v0' do
    get '/news', to: 'application#news'
    post '/contact', to: 'application#contact', as: 'contact'
    get '/flush', to: 'application#flush_cache', as: 'flush_cache'
    post '/email', to: 'application#send_email', as: 'email'
  end

  get '/unsubscribe', to: 'application#unsubscribe', as: 'unsubscribe'
end

app/controllers/admin/listings_controller.rb
include ActionView::Helpers::TextHelper
class Admin::ListingsController < Admin::BaseController
  def users
    @users = User.all
    @users = @users.order_by(sort_users(params[:sort] ||= ''))
    @users = @users.page(params[:page]).per(20)
  end

  def moderate
    if !params[:type] || params[:type].blank?
      flash[:alert] = t('admin.listings.please_specify')
      return redirect_to :back
    end
    object = params[:type].singularize.classify.constantize
    count = params[:objects].count ||= 0
    failed = 0
    params[:objects].each do |k, v|
      o = object.find(k)
      o ? o.destroy : failed += 1
    end
    flash[:notice] = "Successfully deleted #{pluralize(count, params[:type].downcase)}."
    if failed > 0
      flash[:notice] += " #{failed} failed."
    end
    redirect_to :back
  end

  def add_blogger
    username = params[:username]
    if user = User.find_by(username: username)
      user.can_blog = true
      user.save
      redirect_to admin_users_path
    else
      return redirect_to admin_users_path, :alert => t('emails.not_found')
    end   
  end

  def remove_blogger
    username = params[:username]
    if user = User.find_by(username: username)
      user.can_blog = false
      user.save
      redirect_to admin_users_path
    else
      return redirect_to admin_users_path, :alert => t('emails.not_found')
    end   
  end

  private
  def sort_users(sort)
    case sort.downcase
    when "username"
      "username ASC"
    when "-username"
      "username DESC"
    when "email"
      "email ASC"
    when "-email"
      "email DESC"
    when "sign_in_count"
      "sign_in_count ASC"
    when "-sign_in_count"
      "sign_in_count DESC"
    else
      "username ASC"
    end
  end
end

app/views/admin/listings/users.html.erb
<div id="centerpage" class="admin">
	<%= render 'shared/tabs' %>
	<div class="box effect1">
		<h2><%= t('admin.titles.user_list') %></h2>
	</div>
	<div id="mainpage">
		<%= form_tag admin_mass_moderation_path, :method => :post do %>
		<% if @users.any? %>
		<table>
			<thead>
				<tr>
					<td><input type="checkbox" id="all" checked='false'></td>
					<th><%= sortable 'username' %></th>
					<th><%= sortable 'email' %></th>
					<th><%= sortable 'admin' %></th>
					<th><%= sortable 'sign_in_count', t('.login_count') %></th>
					<th><%= sortable 'banned', t('.banned') %></th>
					<th title="Click to change user's permissions."><%= sortable 'can_blog', t('.blogger') %></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= check_box_tag("objects[#{user.id}]", 1, false, class: 'content-check') %></td>
					<td><%= link_to user.username, user_uploads_path(user.username), title: t('.go_to_profile') %></td>
					<td><%= link_to user.email, admin_email_path(username: user.username), title: t('admin.titles.send_email') %></td>
					<td><%= user.admin %></td>
					<td><%= user.sign_in_count %></td>
					<td>
					<% if !user.banned %>
					<%= link_to t('ban_user'), ban_user_path(username: user.username), method: :post %>
					<% else %>
					<%= link_to t('unban_user'), ban_user_path(username: user.username), method: :post %>
					<% end %>
					</td>
					<td>
					<% if !user.can_blog %>
					<%= link_to t('No'), admin_add_blogger_path(username: user.username), method: :post %>
					<% else %>
					<%= link_to t('Yes'), admin_remove_blogger_path(username: user.username), method: :post %>
					<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= hidden_field_tag :type, 'User' %>
		<div id='content-paginator' align='center' class='pagination-wrap'>
			<div class='action'>
				<%= select_tag :action, options_for_select([['Delete', 'delete']], "Delete") %>
				<%= submit_tag t('common.confirm'), data: { confirm: t('common.sure') } %>
			</div>
			<%= paginate @users %>
		</div>
		<% else %>
		<p align="center" id="none"><%= t '.no_users' %></p>
		<% end %>
		<% end %>
	</div>
</div>