config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'control#index'
    get 'moderation', to: 'moderation#index'
    get 'email', to: 'control#email'
    get 'stats', to: 'stats#index'
    resources :reports do
      get :delete_content
      get :resolve
      get :deny
      get :reopen
      get :close
    end
    scope '/lists' do
      get 'users', to: 'listings#users'
      post 'add_blogger', to: 'listings#add_blogger'
      post 'remove_blogger', to: 'listings#remove_blogger'
      post 'mass_moderation', to: 'listings#moderate'
    end
  end

  post 'ban_user', to: 'application#ban_user'
    post 'unban_user', to: 'application#unban_user'

  get '/c/:category', to: 'submissions#index', as: 'category'
  get '/all', to: 'submissions#index'
  get '/search', to: 'submissions#search', as: 'search'

  # Users
  devise_for :users, :controllers => { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks', :passwords => 'usesr/passwords' }  
  get '/u/:user', to: 'submissions#user', as: 'user_uploads'
  get '/accounts/finish_steam', to: 'application#finish_steam', as: 'finish_steam'
  # Root
  root 'home#home'

  get '/home', to: 'home#home'

  # About Page
  get :about, to: 'home#about'

  # Submissions
  get '/projects/:type', to: 'submissions#index', as: 'projects', defaults: { :type => 'all' }
  resources :submissions do
    # Latest download
    get :download
    resources :comments do
      get :restore
    end
    resources :uploads do
      post :approve
      post :deny
      # Download specific version
      get :download
    end
    resources :images, :only => [:edit, :create, :destroy, :new]
    get :favorite
    resources :videos
    resources :reports
  end

  namespace :blog do
    get '/', to: 'posts#index'
    resources :posts
  end

  resources :uploads do
    post :approve
    post :deny
  end

  resources :comments do
    resources :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/documentation', to: 'documentation#index', defaults: { format: 'html' }
      resources :submissions, :only => [:show, :index], defaults: { :sort => 'popular', :type => 'all' } do
        resources :comments, :only => [:show, :index]
        resources :uploads, :only => [:show, :index]
      end
      scope 'stats' do
        get :submissions, :to => 'submissions#stats'
        get :uploads, :to => 'uploads#stats'
        get :comments, :to => 'comments#stats'
      end
    end
  end

  scope '/api/v0' do
    get '/news', to: 'application#news'
    post '/contact', to: 'application#contact', as: 'contact'
    get '/flush', to: 'application#flush_cache', as: 'flush_cache'
    post '/email', to: 'application#send_email', as: 'email'
  end

  get '/unsubscribe', to: 'application#unsubscribe', as: 'unsubscribe'
end

app/views/shared/_alerts.html.erb
<% if notice %>
	<div class="notificationwrap notice">
		<span class="notificationtext"><%= notice %></span><a class="notificationclosebutton" href="#">&times;</a>
	</div>
<% elsif alert %>
	<div class="notificationwrap alert">
		<span class="notificationtext"><%= alert %></span><a class="notificationclosebutton" href="#">&times;</a>
	</div>
<% end %>

app/views/shared/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55393401-1', 'auto');
  ga('send', 'pageview');

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<% object.errors.full_messages.each_with_index do |msg, i| %>
		<% if i != 0 %>
			<br>
		<% end %>
		<%= msg %>
	<% end %>
<% end %>

app/views/shared/_footer.html.erb
<div id="footerpage">
  <table class="footertable">
    <tr>
      <td><%= link_to t('.about'), about_path %></td>
      <td><%= link_to t('.contact'), '#contact-popup', class: 'contact-button' %></td>
      <td><%= link_to t('common.submit'), new_submission_path %></td>
    </tr>
    <tr>
      <td colspan="3" class="socialmedialogos">
        <%= link_to image_tag('facebook.png', class: 'socialmediaimg', alt: t('.facebook')), "https://www.facebook.com/pages/Mods-Unturnedcom/846719095349217", target: "_blank" %>
        <%= link_to image_tag('twitter.png', class: 'socialmediaimg', alt: t('.twitter')), "https://twitter.com/Mods_Unturned", target: "_blank" %>
        <%= link_to image_tag('google.png', class: 'socialmediaimg', alt: t('.google')), "https://plus.google.com/103886656948838780928/about", target: "_blank" %>
        <%= link_to image_tag('youtube.png', class: 'socialmediaimg', alt: t('.youtube')), "", target: "_blank" %>
      </td>
    </tr>
  </table>
</div>

<div id="contact-popup" class="mfp-hide mfp-with-anim">
  <p>
    <%= t '.please_allow' %>
  </p>
  <%= form_tag contact_path, method: 'POST' do %>
  <%= label_tag 'Username', t('activerecord.attributes.user.username') %> <%= text_field :contact, :username, class: 'contactboxes', value: current_user ? current_user.username : "" %>
  <%= label_tag 'Email', t('activerecord.attributes.user.email') %> <%= email_field :contact, :email, class: 'contactboxes', value: current_user ? current_user.email : "" %>
  <%= label_tag 'Message', t('.message') %><%= text_area :contact, :inquiry, class: 'contactboxes', rows: 7 %>
  <%= submit_tag t('common.send'), class: 'contactsubmitbutton', :data => { :disable_with => t('common.sending') } %>
  <div class="g-recaptcha" data-sitekey="6LdXLQITAAAAAH39kLpg0OWSOEyIe5WgrMWbx00F"></div>
  <% end %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55393401-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_tabs.html.erb
<div id="headerpage">
  <div class="logoheaderbar">
    <div class="logowrap">
      <%= link_to (image_tag "logo.png", alt: "Mods-Unturned"), root_path %>
        <%= link_to new_submission_path do %>
        <div class="addmodbutton"><%= t('.add_mod') %></div>
        <% end %>
      <ul>
        <li>
          <a class="username" href="#"><%= current_user ? current_user.username[0, 15] : "Account" %></a>
          <%= image_tag 'downarrow.png', class: 'downarrow' %>
        </li>
        <ul>
            <% if current_user %>
              <li>
                <div class="downarrowoptions"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
              </li>
              <li>
                <div class="downarrowoptions"><%= link_to 'Uploads', user_uploads_path(current_user.username) %></div>
              </li>
            <% else %>
            <li><div class="downarrowoptions"><%= link_to 'Log in', '#login-popup', class: 'login-button' %></div></li>
            <% end %>
        </ul>
      </ul>
    </div>
  </div>
  <div class="categorynavigation">
    <%= link_to root_path do %>
    <div class="category">
      <%= image_tag 'homeicon50.png', alt: 'Home' %>
      <h1>Home</h1>
    </div>
    <% end %>

    <%= category('Weapons', 'weaponsicon50.png') %>
    <%= category('Maps', 'mapsicon50.png') %>
    <%= category('Vehicles', 'vehiclesicon50.png') %>
    <%= category('Misc', 'miscicon50.png') %>

    <div class="category searchwrap">
      <%= form_tag search_path, method: 'GET' do %>
      <%= text_field :search, :search, class: 'search', placeholder: 'Search', value: params[:search] ? params[:search][:search] : "", autocomplete: 'off' %>
      <%= image_submit_tag 'searchicon.png', class: 'searchbutton' %>
      <% end %>
    </div>
  </div>

  <div class="headerbackground"></div>
</div>

<% if !current_user %>
<div id='reset-popup' class="resetpassword_popupwrap mfp-hide mfp-with-anim">
  <div class="popuptoptitlewrap">
    <h1> <%= t('.password_reset') %> </h1>
  </div>
  <div class="passwordreset_inputwrap">
    <%= form_for :user, as: :user, url: password_path(:user, format: :json), remote: true, method: :post, html: { style: 'margin-bottom: 0px', id: 'send_email' } do |f| %>
    <%= f.email_field :email, autofocus: true, class: 'email-input', autocomplete: 'off', type: 'email', placeholder: 'Email' %>
    <div class="passwordreset_notificationmessagewrap errormessage"><span class="passwordreset_notificationtext"><%= t('.an_email') %></span></div>
    <a class="submitlink" href="#"><%= f.submit t('common.submit'), class: 'signinbutton', :data => { :disable_with => t('common.submitting') } %></a>
    <% end %>
    <div class="passwordreset_inputbottomwrap">
    </div>
  </div>
</div>

<div id='login-popup' class="popupwrap mfp-hide mfp-with-anim">
  <div class="popuptoptitlewrap">
    <h1> <%= t('.log_in_panel') %> </h1>
  </div>
  <div class="signinwrap">
    <div class="inputwrap">
      <%= form_for(:user, url: user_session_path(format: :json), remote: true, format: :json, :html => { :style => 'margin-bottom: 0px;', :id => "log_in_user" }) do |f| %>
      <%= f.text_field :login, class: 'login-input', autocomplete: 'off', type: 'text', placeholder: t('users.email_or_username') %>
      <%= f.password_field :password, class: 'login-input', autocomplete: 'off', type: 'password', placeholder: t('activerecord.attributes.user.password') %>
      <div class="forgotwrap"> <%= link_to t('users.forgot_details'), '#reset-popup', class: 'reset-link-button' %></div>
      <a class="submitlink" href='#'><%= f.submit t('users.log_in'), class: 'signinbutton' %></a>
      <% end %>

      <div class="inputbottomwrap">
        <div class="notificationmessagewrap errormessage"><span class="notificationtext"><%= t('users.welcome_back') %></span></div>
        <%= link_to image_tag('steambutton.png', alt: t('users.log_in_steam'), class: 'steamloginbutton'), user_omniauth_authorize_path(:steam)  %></a>
      </div>
    </div>
  </div>

  <div class="registerwrap">
    <div class="inputwrap register">
      <%= form_for(:user, url: user_registration_path(format: :json), remote: true, format: :json, :html => { :style => 'margin-bottom: 0px;', :id => "register_user" }) do |f| %>
      <%= f.email_field :email, class: 'register-input', autocomplete: 'off', type: 'email', placeholder: t('activerecord.attributes.user.email') %>
      <%= f.text_field :username, class: 'register-input', autocomplete: 'off', type: 'text', placeholder: t('activerecord.attributes.user.username') %>
      <%= f.password_field :password, class: 'register-input', autocomplete: 'off', type: 'password', placeholder: t('activerecord.attributes.user.password') %>
      <%= f.password_field :password_confirmation, class: 'register-input', autocomplete: 'off', type: 'password', placeholder: t('devise.passwords.form.confirm_password') %>
      <a class="submitlink" href='#'><%= f.submit t('users.register'), class: 'registerbutton' %></a>
      <% end %>

      <div class="inputbottomwrap">
        <div class="notificationmessagewrap errormessage"><span class="notificationtext"><%= t('users.join_us') %></span></div>
        <div class="registercircleinfo"><div class="circletext"><%= t('common.upload') %></div></div>
        <div class="registercircleinfo"><div class="circletext"><%= t('comments.form.comment') %></div></div>
        <div class="registercircleinfo"><div class="circletext"><%= t('common.manage') %></div></div>
      </div>
    </div>  
  </div>
</div>
<% end %>