config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'control#index'
    get 'moderation', to: 'moderation#index'
    get 'email', to: 'control#email'
    get 'stats', to: 'stats#index'
    resources :reports do
      get :delete_content
      get :resolve
      get :deny
      get :reopen
      get :close
    end
    scope '/lists' do
      get 'users', to: 'listings#users'
      post 'add_blogger', to: 'listings#add_blogger'
      post 'remove_blogger', to: 'listings#remove_blogger'
      post 'mass_moderation', to: 'listings#moderate'
    end
  end

  post 'ban_user', to: 'application#ban_user'
    post 'unban_user', to: 'application#unban_user'

  get '/c/:category', to: 'submissions#index', as: 'category'
  get '/all', to: 'submissions#index'
  get '/search', to: 'submissions#search', as: 'search'

  # Users
  devise_for :users, :controllers => { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks', :passwords => 'usesr/passwords' }  
  get '/u/:user', to: 'submissions#user', as: 'user_uploads'
  get '/accounts/finish_steam', to: 'application#finish_steam', as: 'finish_steam'
  # Root
  root 'home#home'

  get '/home', to: 'home#home'

  # About Page
  get :about, to: 'home#about'

  # Submissions
  get '/projects/:type', to: 'submissions#index', as: 'projects', defaults: { :type => 'all' }
  resources :submissions do
    # Latest download
    get :download
    resources :comments do
      get :restore
    end
    resources :uploads do
      post :approve
      post :deny
      # Download specific version
      get :download
    end
    resources :images, :only => [:edit, :create, :destroy, :new]
    get :favorite
    resources :videos
    resources :reports
  end

  namespace :blog do
    get '/', to: 'posts#index'
    resources :posts
  end

  resources :uploads do
    post :approve
    post :deny
  end

  resources :comments do
    resources :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/documentation', to: 'documentation#index', defaults: { format: 'html' }
      resources :submissions, :only => [:show, :index], defaults: { :sort => 'popular', :type => 'all' } do
        resources :comments, :only => [:show, :index]
        resources :uploads, :only => [:show, :index]
      end
      scope 'stats' do
        get :submissions, :to => 'submissions#stats'
        get :uploads, :to => 'uploads#stats'
        get :comments, :to => 'comments#stats'
      end
    end
  end

  scope '/api/v0' do
    get '/news', to: 'application#news'
    post '/contact', to: 'application#contact', as: 'contact'
    get '/flush', to: 'application#flush_cache', as: 'flush_cache'
    post '/email', to: 'application#send_email', as: 'email'
  end

  get '/unsubscribe', to: 'application#unsubscribe', as: 'unsubscribe'
end

app/models/report.rb
class Report
  include Mongoid::Document
  include Mongoid::Timestamps

  before_save :set_resolved
  
  validates :report_type, presence: true, inclusion: { in: ['Spam', 'Inappropriate', 'Not Original', 'Other'], message: "Invalid report type."}
  validates :status, inclusion: { in: ['Active', 'Denied', 'Content Deleted', 'Resolved', 'Closed'] }
  validate :one_per_user

  field :report_type, type: String, default: 'Spam'
  field :comments, type: String
  field :status, type: String, default: 'Active'
  field :resolved_at, type: Time

  belongs_to :resolver, class_name: 'User', inverse_of: :created_reports # report resolver
  belongs_to :reporter, class_name: 'User', inverse_of: :resolved_reports # report creator

  belongs_to :reportable, polymorphic: true

  def one_per_user
    errors.add(:base, "You already have an active report for this content.") if self.reporter.created_reports.where(:reportable => reportable).where(:status => 'Active').any?
  end

  def set_resolved
    self.resolved_at = Time.now unless !self.resolver
  end

  def delete_content(completed_by)
    self.status = 'Content Deleted'
    self.resolver = completed_by
    reportable.destroy
    self.save
  end

  def resolve(completed_by)
    self.status = 'Resolved'
    self.resolver = completed_by
    self.save
  end

  def close(completed_by)
    self.status = 'Closed'
    self.resolver = completed_by
    self.save
  end

  def reopen(completed_by)
    self.status = 'Active'
    self.resolved_at = nil
    self.resolver = nil
    self.save
  end

  def deny(completed_by)
    self.status = 'Denied'
    self.resolver = completed_by
    self.save
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController
  before_filter :set_report, only: [:show, :delete_content, :deny, :resolve, :close, :reopen]

  def index
    if !params[:status] || params[:status] == 'active'
      @reports = Report.where(:status => 'Active')
    elsif params[:status] == "closed"
      @reports = Report.ne(:status => "Active")
    elsif params[:status]
      @reports = Report.where(:status => params[:status].titleize)
    end
  end

  def show
    redirect_to admin_reports_path unless @report
  end

  def delete_content
    @report.delete_content(current_user)
    redirect_to admin_reports_path, :notice => t('admin.reports.successfully_deleted_content')
  end

  def deny
    @report.deny(current_user)
    redirect_to admin_reports_path, :notice => t('admin.reports.successfully_denied')
  end
  
  def resolve
    @report.resolve(current_user)
    redirect_to admin_reports_path, :notice => t('admin.reports.successfully_resolved')
  end

  def reopen
    @report.reopen(current_user)
    redirect_to admin_report_path(@report), :notice => t('admin.reports.successfully_reopened')
  end

  def close
    @report.close(current_user)
    redirect_to admin_reports_path, :notice => t('admin.reports.successfully_closed')
  end

  private
  def set_report
    @report = Report.find(params[:id] || params[:report_id])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_ban, only: [:create]

  def create
    @reportable = find_reportable
    @report = @reportable.reports.build(report_params)
    @report.reporter = current_user
    if @report.save
      redirect_to @reportable, :notice => t('reports.successfully_reported')
    else
      redirect_to @reportable, :alert => t('reports.unable_to_report')
    end
  end

  private
  def report_params
    params.require(:report).permit(:report_type, :comments)
  end

  def find_reportable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
  def report_content(report)
    return nil if !report.reportable
    if report.reportable_type == 'Comment'
      return report.reportable.text
    elsif report.reportable_type == 'Submission'
      return report.reportable.name
    end
  end
end

app/views/admin/reports/index.html.erb
<div id="centerpage" class="admin">
  <%= render 'shared/tabs' %>
  <div class="box effect1">
    <h2><%= t '.report_moderation' %></h2>
  </div>
  <div id="mainpage">
    <p class='selector'>
      <% if params[:status] == "active" || !params[:status] %>
      <b>
        <%= link_to (t '.active'), params.merge(:status => "active") %>
      </b>
      <% else %>
      <%= link_to (t '.active'), params.merge(:status => "active") %>
      <% end %>
      <% if params[:status] == "closed" %>
      &bull;
      <b>
        <%= link_to (t '.closed'), params.merge(:status => "closed") %>
      </b>
      <% else %>
      &bull;
      <%= link_to (t '.closed'), params.merge(:status => "closed") %>
      <% end %>
    </p>
    <% if @reports.any? %>
    <table class='moderation'>
      <tr>
        <th><%= t '.content' %></th>
        <th><%= t '.reason' %></th>
        <th><%= t '.date_reported' %></th>
        <th><%= t 'reports.common.reporter' %></th>
      </tr>
      <% @reports.each do |report| %>
      <tr>
        <td>
          <% if !report.reportable %>
          Deleted
          <% else %>
          <%= link_to report.reportable.class.name.to_s, report.reportable %>
          <% end %>
        </td>
        <td>
          <%= link_to report.report_type, admin_report_path(report) %>
        </td>
        <td title="<%= report.created_at %>">
          <%= time_ago_in_words(report.created_at) + ' ago' %>
        </td>
        <td>
          <%= link_to report.reporter.username, user_uploads_path(report.reporter.username) %>
        </td>
      </tr>
      <% end %>
    </table>
    <% else %>
    <p align="center" id="none"><%= t '.no_reports' %></p>
    <% end %>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div id="centerpage" class="admin">
	<%= render 'shared/tabs' %>
	<div class="box effect1">
		<h2><%= t '.report_moderation' %></h2>
	</div>
	<div id="mainpage">
		<table class='report'>
			<tr>
				<th class='reporter-avatar'><%= avatar(@report.reporter, alt: @report.reporter.username) %></th>
				<th class='reporter-info'>
					<h1><%= @report.reporter.username %></h1>
					<span><%= pluralize(@report.reporter.created_reports.count, 'Total Report') %></span>
					<span><%= pluralize(@report.reporter.created_reports.where(:statue => 'Active').count, 'Active Report') %></span>
				</th>
				<th class='resolver-info'>
					<h1><%= @report.resolver ? + @report.resolver.username : 'Unresolved' %></h1>
					<span><%= pluralize(@report.reporter.created_reports.count, 'Total Report') %></span>
					<span><%= pluralize(@report.reporter.created_reports.where(:statue => 'Active').count, 'Active Report') %></span>
				</th>
				<th  class='resolver-avatar'><%= @report.resolver ? avatar(@report.resolver) : image_tag('unknown.png') %></th>
			</tr>
			<tr>
				<th colspan="2"><%= t('.content_type') %></th>
				<th colspan="2"><%= @report.reportable_type %></th>
			</tr>
			<tr>
				<th colspan="2"><%= t('.status') %></th>
				<th colspan="2"><%= @report.status %></th>
			</tr>
			<tr>
				<th colspan="2"><%= t('.content') %></th>
				<th colspan="2">
					<% content = report_content(@report) %>
					<% if content %>
					<%= link_to content, @report.reportable %></th>
					<% else %>
					<%= t('common.deleted') %>
					<% end %>
				</th>
			</tr>
			<tr>
				<th colspan="2"><%= t('.report_comments') %></th>
				<th colspan="2"><%= @report.comments %></th>
			</tr>
			<table class='moderation actions-table'>
				<tr class='actions'>
					<th><%= link_to t('.delete_content'), admin_report_delete_content_path(@report) %></th>
					<th><%= link_to t('.resolve_content'), admin_report_resolve_path(@report) %></th>
					<th><%= link_to t('.deny_report'), admin_report_deny_path(@report) %></th>
					<% if @report.resolved_at %>
					<th><%= link_to t('.reopen_report'), admin_report_reopen_path(@report) %></th>
					<% else %>
					<th><%= link_to t('.close_report'), admin_report_close_path(@report) %></th>
					<% end %>
				</tr>
			</table>
		</table>
	</div>
</div>